### ISSUE TITLE
Project conventions

### ISSUE THREAD

**Issue by niquola** [lhncbc/fhirpath.js#2]
Should we use `src` dir for sources and `test` for tests?
Are we going use jest for tests?
Are we going use travis CI?
Who will create npm package?

**Comment by plynchnlm** [comment]
So, in the last day or two I have been working on a new branch with changes that include the beginning on an interpreter and some other things.  It is not quite working yet, and I haven't gotten to writing tests, but I could push it out on the side branch so you can see the current structure.  I don't object to moving things under src if you prefer that after taking a look.

I was planning on putting tests under "test", and probably using mocha, so those would be under test/mocha.  I was also planning to use Grahame's XML tests, converted to JSON, but only a handful that the new engine actually supports.

I had not heard of "jest" until just now.  Is it better than mocha?  It looks rather similar.

My usual practice is to require tests pass (and exist) before merging to master, so we do not use a CI.  Would it provide any benefit?

I can create the npm package, but I would like to wait until after my initial goal of processing "Patient.name.given" is reached (probably with the next pull request).

**Comment by niquola** [comment]
let’s work together on same branch, i almost prepared tests infrastructure, travis etc. I think first month we can work in master without strict review and later switch to more formal pull-requests

**Comment by niquola** [comment]
tru ci is commit to master n times in a day ;)

**Comment by niquola** [comment]
i will add travis - so we can breake master and fix it quckly

**Comment by niquola** [comment]
jest  now is considered best by js community, it’s not very different from mocha. Can you push all of you changes as often as possible.

**Comment by plynchnlm** [comment]
I don't think working on the same branch is a good idea.  I am used to each branch being worked on by one developer for a particular feature or goal, ideally containing not more than 2-3 days work so that it can be thoroughly reviewed.  By keeping to separate branches, it will be easier to separate our work so we do not end up doing the same tasks.

With work on separate development branches, I don't see the point of pushing changes that are not working or ready for review, but I'm willing to do it once a day so you can see what progress I've made.

If you are going to be actively contributing a lot, we should coordinate more, and organize work into planned tasks with defined boundaries.  Here an NLM we use JIRA for that, and do sprint planning.

I am fine with giving jest a try.

**Comment by niquola** [comment]
I'm interested in more active contribution. Can i provide alternative initial implementation, then we can take best of both? As well i can pull request infrastructure setup.

**Comment by plynchnlm** [comment]
Let's hash out the rest of this on Zulip.
