### ISSUE TITLE
I think isSome() always returns false here.

### ISSUE THREAD

**Issue by akanduru** [lhncbc/fhirpath.js#21]
#https://github.com/lhncbc/fhirpath.js/blob/4e7091f019c020b400b707a8c5b7ee1fab425f71/src/fhirpath.js#L46

**Comment by niquola** [comment]
Why?
Here is the body of isSome
```
 return x !== null && x !== undefined && !isEmpty(x);
```
before there is check for array, otherwise this line is executed - so for everything which is not null or undefined it will returns true.

You can write tests for isSome and arraify functions :)
I think, when we implement essential part of spec - we will do refactoring and reduce code twice :)
But we need to see all cases

**Comment by akanduru** [comment]
There is nothing wrong with isSome() function itself. 

I was referring to its usage on line 46 in fhirpath.js. If it is an array it never reaches line 46. If it is not, isSome() always returns false. So, the line 46 is redundant.

**Comment by akanduru** [comment]
I misunderstood the meaning of isSome(). It returns true on anything that is not an array!
