### ISSUE TITLE
Incorrect case in 5.6_string_manipulation.yaml

### ISSUE THREAD

**Issue by Bolik** [lhncbc/fhirpath.js#76]
- desc: '** replaceMatches 2'
    expression: Functions.str.date.replace('\\b(?<month>\\d{1,2})/(?<day>\\d{1,2})/(?<year>\\d{2,4})\\b', '${day}-${month}-${year}')
    disable: true
    result: ['30-11-1972']

replace doesn't allow regex as argument. It was a typo in spec, and it was copied to this test.

**Comment by plynchnlm** [comment]
It looks like it should have been replaceMatches.  That is easy to change.

However, it seems that named capturing groups are not supported by node.js.  I will probably revise the test to just use $1, $2, and $3.

Another problem is that I think fhirpath.js is not correctly interpreting the escape sequences in the string, which means the test still won't pass unless that problem is fixed.

**Comment by plynchnlm** [comment]
This is now fixed (using $1, $2, etc.) in 0.12.0.  (See the new location of this repository at https://github.com/HL7/fhirpath.js; this one will be deleted soon.)
